name: "TEST"

on:
  workflow_dispatch:
  push:
    tags-ignore:
      - '**'
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    steps:
      - name: "Validate Input"
        id: "inputs"
        run: |
          echo "--------------------- VALIDATION ---------------"
          if [ "$GITHUB_ACTOR" != "YunaBraska" ]; then echo "Permission denied for user [$GITHUB_ACTOR]"; exit 1; fi
          echo "--------------------- ENVS ---------------------"
          env
      - name: "Checkout"
        uses: actions/checkout@main
      - name: "Setup Node"
        uses: actions/setup-node@main
        with:
          node-version: "16"
          cache: npm
      - name: "update dependencies"
        run: |
          npm outdated || true 
          npm update --save
          npm audit fix --force
      - name: "Run Tests"
        run: |
          npm ci && npm run test:coverage
      - name: "Get Java Version"
        id: "read_java"
        uses: YunaBraska/java-info-action@main
        with:
          work-dir: '.'
          deep: '-1'
          jv-fallback: 8
          pv-fallback: '0.0.1'
      - name: "Validate Java Version"
        run: |
          echo "java_version [${{ steps.read_java.outputs.java_version }}]"
          echo "artifact_name [${{ steps.read_java.outputs.artifact_name }}]"
          echo "project_version [${{ steps.read_java.outputs.project_version }}]"
          echo "project_encoding [${{ steps.read_java.outputs.project_encoding }}]"
          echo "is_gradle [${{ steps.read_java.outputs.is_gradle }}]"
          echo "is_maven [${{ steps.read_java.outputs.is_maven }}]"
          echo "has_wrapper [${{ steps.read_java.outputs.has_wrapper }}]"
          echo "builder_name [${{ steps.read_java.outputs.builder_name }}]"
          echo "x_sourceCompatibility [${{ steps.read_java.outputs.x_sourceCompatibility }}]"
          echo "x_project_build_finalName [${{ steps.read_java.outputs.x_project_build_finalName }}]"
          echo "x_groovyOptions_encoding [${{ steps.read_java.outputs.x_groovyOptions_encoding }}]"
          echo "X_net_minidev_json-smart_version [${{ steps.read_java.outputs.x_project_dependencies_dependency_net_minidev_json-smart_version }}]"
          if [ "${{ steps.read_java.outputs.java_version }}" != "17" ]; then echo "Unexpected Java Version [${{ steps.read_java.outputs.java_version }}] should have been 17"; exit 1; fi
